# Starter pipeline
- task: katalonTask@0
  inputs:
    version: '7.9.1'
    executeArgs: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/ProAcc_Suite"'
- task: katalonTask@0
  inputs:
    version: '7.9.1'
    executeArgs: 'katalonc -noSplash -runMode=console -projectPath="C:\Users\Group10\git\ProAcc_Update2.0NewUI\ProAcc_Update2.0NewUI.prj" -retry=0 -testSuitePath="Test Suites/ProAcc_Suite" -executionProfile="ProAcc" -browserType="Chrome (headless)"'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
