<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>confirmpassword</description>
   <name>confirmpassword</name>
   <tag></tag>
   <elementGuidId>c3ca23ad-3651-446e-b3d3-fc9f323fdb8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCnfmPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
